### ISSUE TITLE
Generate report in XML?

### ISSUE THREAD

**Issue by MarkSkillen** [vrondakis/zap-jenkins-pipeline-plugin#8]
Hi,
Does your plugin allow the user at all to specify the output format of the test once the process is finished? In order to work with the likes of OWASP DefectDojo (which says it will only work with the XML formatted output from ZAP).
Reading your documentation, and looking at the source code, it wasn't clear that through the groovy coding in the Jenkinsfile that a user could declare this ? (if not, I might look to implement this and open up a PR)
Thanks

**Comment by vrondakis** [comment]
Hey

This currently can't be done. It wouldn't be difficult to add a download as XML button to the report. I can take a look at adding that soonish or feel free to make a PR (but make sure to use the new repo:  https://github.com/jenkinsci/zap-pipeline-plugin )

Thanks

**Comment by vrondakis** [comment]
Added in 1.8
